ServiceHost/Controllers/EducationController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Application.Services.Interface.Education;

namespace ServiceHost.Controllers
{
    public class EducationController : SiteBaseController
    {
        #region Fields

        private readonly IEducationService _educationService;



        #endregion


        #region Constructor

        public EducationController(IEducationService educationService)
        {
            _educationService = educationService;
        }

        #endregion


        #region Actions

        public ActionResult Resume()
        {
            return View();
        }

        #endregion


    }
}

ServiceHost/ViewComponents/SiteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Application.Services.Interface.User;

namespace ServiceHost.ViewComponents
{
	#region Site Header

	public class SiteHeaderViewComponent : ViewComponent
	{
		private readonly IUserService _userService;

		public SiteHeaderViewComponent(IUserService userService)
		{
			_userService = userService;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var user = await _userService.GetUserDetail();
			return View("SiteHeader",user);
		}
	}

	#endregion

	#region Site Footer

	public class SiteFooterViewComponent : ViewComponent
	{
		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View("SiteFooter");
		}
	}

	#endregion
}

ServiceHost/Views/Shared/_FooterRefererences.cshtml
<script src="~/MainSite/assets/js/jquery-3.4.1.min.js"></script>
<script src="~/MainSite/assets/js/plugins.min.js"></script>
<script src="~/MainSite/assets/js/common.js"></script>

ServiceHost/Views/Shared/_HeaderReferences.cshtml
<!-- Favicons -->
<link rel="apple-touch-icon" sizes="144x144" href="~/MainSite/assets/images/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="114x114" href="~/MainSite/assets/images/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="~/MainSite/assets/images/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="57x57" href="~/MainSite/assets/images/favicons/apple-touch-icon-57x57.png">
<link rel="shortcut icon" href="~/MainSite/assets/images/favicons/favicon.png" type="image/png">

<!-- Styles -->
<link rel="stylesheet" type="text/css" href="~/MainSite/assets/styles/style-rtl-demo.css" />
<link rel="stylesheet" type="text/css" href="~/MainSite/assets/styles/style-dark.css" />
<link rel="stylesheet" type="text/css" href="~/MainSite/assets/styles/style-rtl.css" />
<link rel="stylesheet" type="text/css" href="~/MainSite/assets/demo/style-demo.css" />

ServiceHost/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
	<meta charset="utf-8" />
	<title>@ViewData["Title"] | به وب سایت شخصی نوید قوامی خوش آمدید</title>

    <partial name="_MetaTags"/>

	<partial name="_HeaderReferences"/>

</head>
<body class="bg-triangles">
	<!-- Preloader -->
	<div class="preloader">
		<div class="preloader__wrap">
			<div class="circle-pulse">
				<div class="circle-pulse__1"></div>
				<div class="circle-pulse__2"></div>
			</div>
			<div class="preloader__progress"><span></span></div>
		</div>
	</div>

	<main class="main">
        <div class="container gutter-top-100">
            <!-- Header -->
            @await Component.InvokeAsync("SiteHeader")

            <div class="row sticky-parent">
                <!-- Sidebar nav -->
                <aside class="col-12 col-md-12 col-lg-2">
                    <div class="sidebar box sticky-column">
                        <ul class="nav">
                            <li class="nav__item"><a class="" href="/"><i class="icon-user"></i>درباره ی ما</a></li>
                            <li class="nav__item"><a asp-controller="Education" asp-action="Resume"><i class="icon-file-text"></i>رزومه من</a></li>
                            <li class="nav__item"><a href="works.html"><i class="icon-codesandbox"></i> کارها</a></li>
                            <li class="nav__item"><a href="blog.html"><i class="icon-book-open"></i>وبلاگ</a></li>
                            <li class="nav__item"><a href="contact.html"><i class="icon-book"></i>تماس با ما</a></li>
                        </ul>
                    </div>
                </aside>

                <!-- Content -->
                @RenderBody()
            </div>
        </div>
        <!-- Footer -->
        @await Component.InvokeAsync("SiteFooter")
	</main>

	<!-- SVG masks -->
	<svg class="svg-defs">
		<clipPath id="avatar-box">
			<path d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z" />
		</clipPath>
		<clipPath id="avatar-hexagon">
			<path d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z" />
		</clipPath>
	</svg>

	<div class="back-to-top"></div>

	<!-- JavaScripts -->
	
	<partial name="_FooterRefererences"/>

    <script src="~/MainSite/assets/demo/plugins-demo.js"></script>
</body>
</html>

ServiceHost/Views/Shared/_MetaTags.cshtml
<!-- Meta Data -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="address=no" />
<meta name="author" content="Navid Ghavami" />
<meta name="description" content="vCard" />

<!-- Twitter data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="vCard">
<meta name="twitter:description" content="vCard">
<meta name="twitter:image" content="assets/images/social.html">

<!-- Open Graph data -->
<meta property="og:title" content="Melika Khaliliyan" />
<meta property="og:type" content="website" />
<meta property="og:url" content="your url website" />
<meta property="og:image" content="assets/images/social.html" />
<meta property="og:description" content="vCard" />
<meta property="og:site_name" content="vCard" />